name: step03_variable
on: workflow_dispatch

env:
  name: Devops

jobs:
  build_1: 
    env: 
      name: Infra
    runs-on: ubuntu-latest
    steps:
    - name: Build_1 Step1
      run: |
        echo "Run Build_1 Step1 : ${{ name }}"
  build_2:
    runs-on: ubuntu-latest
    steps:
    - name: Build_2 Step1
      run: |
        echo "Run Build_2 Step1 : $name"
